hba_file = '/etc/pg_hba.conf'

listen_addresses = '*'
log_destination = 'stderr'          
logging_collector = on
log_directory = 'log'                 
log_hostname = on

log_statement = 'all'                  
log_min_duration_statement = 0      
log_duration = on
log_connections = on
log_disconnections = on

log_min_messages = info
log_error_verbosity = verbose

log_rotation_age = 30d
log_rotation_size = 5MB